### ISSUE TITLE
Can't upload EPUB files

### ISSUE THREAD

**Issue by jveronese** [rmusser01/tldw#339]
**Are You on the Latest version?**
You did a git pull and are running the latest version/build?
Yes

**Please describe the bug**
I go to upload a .epub file, but receive an error that the filetype is invalid and I need to upload an .epub or .zip

**Is the bug reproducable reliably?**
Yes, happens every time

**Steps to to reproduce the issue**
1. Go to Ingest
2. Choose upload epub
3. attempt to upload an epub file

**What was the expected behavior?**
That epub would upload and process

**Desktop (please complete the following information):**
TLDW - Running on Ubuntu 24.04 install with Ollama
My Desktop - 
    OS- MacOS Sequoia 15.0.1
    Browser - Chrome 129.0.6668.90

**Comment by rmusser01** [comment]
Thank you for the heads up, I will look at this later today.

**Comment by rmusser01** [comment]
The issue should be resolved now. Please perform a pull to update your local copy and retry, it should work.

**Comment by jveronese** [comment]
Did a fresh pull (from both the update script and a git clone of the repo) and I am still getting the error. Here is my terminal output from the server, maybe it helps.

```
Traceback (most recent call last):
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2012, in process_api
    inputs = await self.preprocess_data(
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1711, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/components/file.py", line 163, in preprocess
    return self._process_single_file(payload)
  File "/home/aiadmin/tldw/venv/lib/python3.10/site-packages/gradio/components/file.py", line 132, in _process_single_file
    raise Error(
gradio.exceptions.Error: "Invalid file type. Please upload a file that is one of these formats: ['.epub', '.zip']"
```
